# Generated by Django 4.2.7 on 2024-06-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSpeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('preview', models.ImageField(help_text='Фото для предварительного просмотра', upload_to='students/reviews-preview', verbose_name='Фото')),
                ('video_url', models.URLField(max_length=255, verbose_name='Ссылка на видео')),
                ('education_level', models.ManyToManyField(blank=True, null=True, to='university.educationlevel', verbose_name='Уровни образования')),
                ('faculty', models.ManyToManyField(blank=True, null=True, related_name='student_speakers', to='university.faculty', verbose_name='Институты')),
            ],
            options={
                'verbose_name': 'Говор студента',
                'verbose_name_plural': 'Говоры студентов',
            },
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='students/reviews', verbose_name='Фото')),
                ('education_level', models.ManyToManyField(blank=True, null=True, to='university.educationlevel', verbose_name='Уровни образования')),
                ('faculty', models.ManyToManyField(blank=True, null=True, related_name='student_reviews', to='university.faculty', verbose_name='Институты')),
            ],
            options={
                'verbose_name': 'Отзыв студента',
                'verbose_name_plural': 'Отзывы студентов',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.FileField(upload_to='partners/logo/', verbose_name='Логотип')),
                ('faculty', models.ManyToManyField(blank=True, related_name='partners', to='university.faculty', verbose_name='Институты')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('title',),
            },
        ),
    ]
