# Generated by Django 4.2.7 on 2024-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_additions', '0002_universityinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityinfo',
            options={'verbose_name': 'Информация об университете', 'verbose_name_plural': 'Информация об университете'},
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='instagram',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='telegram',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='Telegram'),
        ),
    ]
