# Generated by Django 4.2.7 on 2024-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_additions', '0003_alter_universityinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='email')),
                ('slug', models.CharField(verbose_name='путь к странице сайте')),
                ('status', models.CharField(choices=[('active', 'активный'), ('passive', 'не активный')], default='active', max_length=15, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Заявка пользователя',
                'verbose_name_plural': 'Заявки пользователей',
                'ordering': ('-created',),
            },
        ),
    ]
