# Generated by Django 4.2.7 on 2024-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_additions', '0004_userapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='name_ky',
            field=models.CharField(max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentspeak',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studentspeak',
            name='description_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studentspeak',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='studentspeak',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentspeak',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentspeak',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
