# Generated by Django 4.2.7 on 2024-12-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_additions', '0005_partner_title_en_partner_title_ky_partner_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.FileField(upload_to='page-item/page-items/', verbose_name='Фото')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.FileField(upload_to='page-item/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('student', 'Student'), ('about', 'About')], max_length=50)),
                ('items', models.ManyToManyField(blank=True, null=True, related_name='page_item', to='university_additions.pageitems', verbose_name='Элементы')),
            ],
        ),
    ]
