# Generated by Django 4.2.7 on 2024-12-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_additions', '0006_pageitems_pageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageitem',
            name='items',
        ),
        migrations.AddField(
            model_name='pageitems',
            name='page_item',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='university_additions.pageitem'),
            preserve_default=False,
        ),
    ]
