# Generated by Django 4.2.7 on 2025-04-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_alter_staff_faculty'),
        ('university_additions', '0009_remove_pageitem_category_pageitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreview',
            name='education_level',
            field=models.ManyToManyField(blank=True, to='university.educationlevel', verbose_name='Уровни образования'),
        ),
        migrations.AlterField(
            model_name='studentreview',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='student_reviews', to='university.faculty', verbose_name='Институты'),
        ),
        migrations.AlterField(
            model_name='studentspeak',
            name='education_level',
            field=models.ManyToManyField(blank=True, to='university.educationlevel', verbose_name='Уровни образования'),
        ),
        migrations.AlterField(
            model_name='studentspeak',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='student_speakers', to='university.faculty', verbose_name='Институты'),
        ),
    ]
