version: '3.9'

services:
  application:
    build:
      context: ./server
    env_file:
      - .env.dev
    container_name: backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app/application
    ports:
      - '8000:8000'
    depends_on:
      - database
    networks:
      - database

  database:
    container_name: database_container
    image: postgres:16.2-alpine3.18
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - '5555:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - database

volumes:
  database-storage:
  pgadmin-data:

networks:
  database:
    driver: bridge