version: '3.9'

services:
  application:
    build:
      context: ./server
    env_file:
      - .env.dev
    container_name: backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app/application
    ports:
      - '8000:8000'
    depends_on:
      - database
      - redis

  database:
    container_name: database_container
    image: postgres:16.2-alpine3.18
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - '5555:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: intuit-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:7.2
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    depends_on:
#      - database

volumes:
  database-storage:
  redis_data:
#  pgadmin-data:
