version: '3.9'

services:
  application:
    build:
      context: ./server
    env_file:
      - .env.dev
    container_name: backend
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app/application
    ports:
      - '8000:8000'
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine3.18
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - '5555:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data

volumes:
  database-storage:
