# Generated by Django 4.2.7 on 2024-06-30 00:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='ссылка')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='education-levels', verbose_name='Фото')),
                ('title_2', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(default='Описание', verbose_name='Описание')),
                ('detail', models.ManyToManyField(to='university.detail', verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='ссылка')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='faculty', verbose_name='Фото')),
                ('detail', models.ManyToManyField(to='university.detail', verbose_name='Детали')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.educationlevel', verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='ссылка')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(default='Описание', verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='programs', verbose_name='Фото')),
                ('detail', models.ManyToManyField(to='university.detail', verbose_name='Детали')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.educationlevel', verbose_name='Уровень образования')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.FileField(upload_to='partners/logo/', verbose_name='Логотип')),
                ('faculty', models.ManyToManyField(related_name='partners', to='university.faculty', verbose_name='Институты')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('title',),
            },
        ),
    ]
