# Generated by Django 4.2.7 on 2024-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_admissioneligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Введите ссылку на профиль (не обязательное полое)', max_length=100, verbose_name='whatsApp'),
        ),
    ]
