# Generated by Django 4.2.7 on 2024-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_position_remove_educationlevel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='video',
        ),
        migrations.RemoveField(
            model_name='studentreview',
            name='video_url',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subtext',
            field=models.CharField(default=1, max_length=255, verbose_name='Под текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='text',
            field=models.CharField(default=1, max_length=255, verbose_name='Главный текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='program_count',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество программ'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='subtext',
            field=models.CharField(max_length=255, verbose_name='Под текст'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Под название'),
        ),
        migrations.AlterField(
            model_name='studentreview',
            name='education_level',
            field=models.ManyToManyField(blank=True, null=True, to='university.educationlevel', verbose_name='Уровни образования'),
        ),
        migrations.CreateModel(
            name='StudentSpeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(help_text='Фото для предварительного просмотра', upload_to='students/reviews-preview', verbose_name='Фото')),
                ('video_url', models.URLField(max_length=255, verbose_name='Ссылка на видео')),
                ('education_level', models.ManyToManyField(blank=True, null=True, to='university.educationlevel', verbose_name='Уровни образования')),
                ('faculty', models.ManyToManyField(blank=True, null=True, related_name='student_speakers', to='university.faculty', verbose_name='Институты')),
            ],
            options={
                'verbose_name': 'Говор студента',
                'verbose_name_plural': 'Говоры студентов',
            },
        ),
    ]
