# Generated by Django 4.2.7 on 2024-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_faculty_description_remove_faculty_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='detail',
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='program_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество программ'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='subtext',
            field=models.TextField(verbose_name='Под текст'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='text',
            field=models.TextField(verbose_name='Главный текст'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subtext',
            field=models.TextField(verbose_name='Под текст'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='text',
            field=models.TextField(verbose_name='Главный текст'),
        ),
    ]
