# Generated by Django 4.2.7 on 2024-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_remove_program_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
        migrations.AddField(
            model_name='program',
            name='education_level',
            field=models.ManyToManyField(to='university.educationlevel', verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ManyToManyField(to='university.faculty', verbose_name='Факультет'),
        ),
    ]
