# Generated by Django 4.2.7 on 2024-07-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_trainingprogram_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programskills',
            name='program',
            field=models.ManyToManyField(blank=True, to='university.program', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='programtools',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Инструмент'),
        ),
        migrations.AlterField(
            model_name='programtools',
            name='program',
            field=models.ManyToManyField(blank=True, to='university.program', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='number',
            field=models.IntegerField(verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='program',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='university.program'),
        ),
    ]
