# Generated by Django 4.2.7 on 2024-07-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_programskills_program_alter_programtools_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingprogramitem',
            old_name='description',
            new_name='name',
        ),
    ]
