# Generated by Django 4.2.7 on 2024-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_program_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
    ]
