# Generated by Django 4.2.7 on 2024-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_faculty_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='banner',
            field=models.ImageField(default=1, upload_to='', verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
