# Generated by Django 4.2.7 on 2024-07-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_programskills_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='text_photo',
            field=models.FileField(default=1, upload_to='programs', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='banner',
            field=models.FileField(upload_to='education-levels', verbose_name='баннер'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='banner',
            field=models.FileField(upload_to='', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='program',
            name='photo',
            field=models.FileField(upload_to='programs', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='programtools',
            name='logo',
            field=models.FileField(upload_to='programs/program-tools/', verbose_name='Лого инструмента'),
        ),
    ]
