# Generated by Django 4.2.7 on 2024-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_program_text_photo_alter_educationlevel_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='photo',
            field=models.FileField(upload_to='programs', verbose_name='Главная фотка'),
        ),
    ]
