# Generated by Django 4.2.7 on 2024-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_programtools_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='faculty_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество факультетов'),
        ),
    ]
