# Generated by Django 4.2.7 on 2024-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_educationlevel_faculty_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='diploma_photo',
            field=models.FileField(default=1, upload_to='education-levels/diploma', verbose_name='Задняя фотка диплома'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProgramProfessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Профессия')),
                ('photo', models.FileField(upload_to='programs/professions/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('program', models.ManyToManyField(blank=True, related_name='professions', to='university.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Профессия программы',
                'verbose_name_plural': 'Профессии программы',
            },
        ),
    ]
