# Generated by Django 4.2.7 on 2024-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_educationlevel_diploma_photo_programprofessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='program_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество программ'),
        ),
    ]
