# Generated by Django 4.2.7 on 2024-11-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_admissioneligibility_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='subtext',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subtext_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subtext_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='program',
            name='subtext_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
