# Generated by Django 4.2.7 on 2024-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_alter_program_subtext_alter_program_subtext_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='faculty/qr_codes/'),
        ),
    ]
