# Generated by Django 4.2.7 on 2025-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0003_alter_documentcollectionitem_document_collection'),
        ('university', '0019_program_contract_price_program_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='document_collections',
            field=models.ManyToManyField(to='document_pages.documentcollection', verbose_name='Коллекции документов'),
        ),
    ]
