# Generated by Django 4.2.7 on 2025-04-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_educationlevel_icon_faculty_icon_program_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='university.faculty', verbose_name='Факультеты'),
        ),
    ]
