# Generated by Django 4.2.7 on 2025-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_alter_staff_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
