# Generated by Django 4.2.7 on 2024-11-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_description_en_post_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description_ug',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_ug',
            new_name='title_ky',
        ),
    ]
