# Generated by Django 4.2.7 on 2024-12-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_alter_program_subtext_alter_program_subtext_en_and_more'),
        ('news', '0005_file_title_en_file_title_ky_file_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faculty',
            field=models.ManyToManyField(related_name='posts', to='university.faculty', verbose_name='Категории2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='news.category', verbose_name='Категории'),
        ),
    ]
