# Generated by Django 4.2.7 on 2024-12-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_staff_qr_code'),
        ('news', '0006_post_faculty_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='posts', to='university.faculty', verbose_name='Категории2'),
        ),
    ]
