# Generated by Django 4.2.7 on 2025-02-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_staff_qr_code'),
        ('news', '0007_alter_post_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'активен'), ('passive', 'не активен')], default='passive', max_length=15, verbose_name='Статус')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique_for_date='date', verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Текст')),
                ('description_ru', models.TextField(null=True, verbose_name='Текст')),
                ('description_en', models.TextField(null=True, verbose_name='Текст')),
                ('description_ky', models.TextField(null=True, verbose_name='Текст')),
                ('banner', models.FileField(upload_to='events/banners/%Y/%m/%d', verbose_name='Баннер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('faculty', models.ManyToManyField(blank=True, related_name='events', to='university.faculty', verbose_name='Категории2')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('-created_at',),
            },
        ),
    ]
