# Generated by Django 4.2.7 on 2025-02-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(verbose_name='Ссылка'),
        ),
    ]
