# Generated by Django 4.2.7 on 2025-05-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
    ]
