# Generated by Django 4.2.7 on 2025-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcollection',
            options={'verbose_name': 'Коллекция документов', 'verbose_name_plural': 'Коллекции документов'},
        ),
        migrations.AlterModelOptions(
            name='documentcollectionitem',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='document_collections',
            field=models.ManyToManyField(to='document_pages.documentcollection', verbose_name='Коллекции документов'),
        ),
    ]
