# Generated by Django 4.2.7 on 2025-02-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0002_alter_documentcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcollectionitem',
            name='document_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_collection_items', to='document_pages.documentcollection'),
        ),
    ]
