# Generated by Django 4.2.7 on 2025-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pages', '0003_alter_documentcollectionitem_document_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcollectionitem',
            options={'ordering': ['order'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='documentcollectionitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
